/**
 * Client access to the precomputed per-hold usage statistics served from
 * /data/hold-stats.json (generated by scripts/hold-stats.ts).
 *
 * For a given angle each hold carries a 24-bucket histogram of the grades of
 * the climbs that use it (bucket 0 = grade 10, bucket 23 = grade 33).
 */

export interface HoldStatsAngle {
  climbs: number;
  mean_grade: number;
  holds: Record<string, number[]>;
}

export interface HoldStatsFile {
  generated_at: string;
  layout: number;
  min_grade: number;
  max_grade: number;
  angles: Record<string, HoldStatsAngle>;
}

export interface HoldStatsSummary {
  /** Climb-stat rows at this angle that include the hold. */
  uses: number;
  /** Total graded climbs at this angle. */
  climbs: number;
  /** Percentage of climbs at this angle that use the hold (0-100). */
  pct: number;
  /** How this hold ranks against every other hold (0-100). */
  percentile: number;
  mean: number;
  median: number;
  p25: number;
  p75: number;
  /** Lowest / highest grade bucket with at least one climb. */
  low: number;
  high: number;
  histogram: number[];
  peak: number;
  minGrade: number;
  maxGrade: number;
}

let cache: Promise<HoldStatsFile | null> | null = null;

export function loadHoldStats(): Promise<HoldStatsFile | null> {
  if (!cache) {
    cache = fetch("/data/hold-stats.json")
      .then((res) => {
        if (!res.ok) {
          cache = null;
          return null;
        }
        return res.json() as Promise<HoldStatsFile>;
      })
      .catch(() => {
        cache = null;
        return null;
      });
  }
  return cache;
}

function totalUses(histogram: number[]): number {
  let n = 0;
  for (const c of histogram) n += c;
  return n;
}

/**
 * Build a display summary for one hold. `totalPlacements` is the number of
 * holds on the board (including ones no climb ever uses) so the percentile
 * rank accounts for unused holds.
 */
export function summarizeHold(
  file: HoldStatsFile,
  angle: number,
  placementId: number,
  totalPlacements: number
): HoldStatsSummary | null {
  const bucket = file.angles[String(angle)];
  if (!bucket) return null;

  const histogram = bucket.holds[String(placementId)];
  const uses = histogram ? totalUses(histogram) : 0;
  const climbs = bucket.climbs || 0;

  // Holds that no climb uses still count when ranking popularity.
  const heldCount = Object.keys(bucket.holds).length;
  const all = Math.max(totalPlacements, heldCount);
  let less = uses > 0 ? Math.max(0, totalPlacements - heldCount) : 0;
  if (uses > 0) {
    for (const other of Object.values(bucket.holds)) {
      if (totalUses(other) < uses) less++;
    }
  }

  const minGrade = file.min_grade;
  const bucketCount = file.max_grade - minGrade + 1;

  if (!histogram || uses === 0) {
    return {
      uses: 0,
      climbs,
      pct: 0,
      percentile: 0,
      mean: 0,
      median: 0,
      p25: 0,
      p75: 0,
      low: minGrade,
      high: minGrade,
      histogram: new Array(bucketCount).fill(0),
      peak: 0,
      minGrade,
      maxGrade: file.max_grade,
    };
  }

  // Weighted mean, quartiles and the observed grade window.
  let sum = 0;
  let acc = 0;
  let median = minGrade;
  let p25 = minGrade;
  let p75 = minGrade;
  let low = minGrade;
  let high = minGrade;
  let peak = 0;
  let gotP25 = false;
  let gotMedian = false;
  let gotP75 = false;

  for (let i = 0; i < histogram.length; i++) {
    const count = histogram[i];
    if (!count) continue;
    const grade = minGrade + i;
    sum += grade * count;
    acc += count;
    if (!gotP25 && acc >= uses * 0.25) {
      p25 = grade;
      gotP25 = true;
    }
    if (!gotMedian && acc >= uses * 0.5) {
      median = grade;
      gotMedian = true;
    }
    if (!gotP75 && acc >= uses * 0.75) {
      p75 = grade;
      gotP75 = true;
    }
    if (acc === count) low = grade;
    high = grade;
    if (count > peak) peak = count;
  }

  return {
    uses,
    climbs,
    pct: climbs > 0 ? (100 * uses) / climbs : 0,
    percentile: all > 0 ? (100 * less) / all : 0,
    mean: sum / uses,
    median,
    p25,
    p75,
    low,
    high,
    histogram,
    peak,
    minGrade,
    maxGrade: file.max_grade,
  };
}
